#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

import { compileQBlade } from "./tools/compiler.js";
import { runQBlade } from "./tools/runner.js";
import { generateQBladeConfig } from "./tools/configGen.js";
import { parseQBladeOutput } from "./tools/parser.js";

// Create server instance
const server = new Server(
  {
    name: "qblade-mcp-server",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// Register tools list
server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "compile_qblade",
        description: "Checks system dependencies and compiles QBladeCE from source using qmake and make.",
        inputSchema: {
          type: "object",
          properties: {
            forceClean: {
              type: "boolean",
              description: "Perform a 'make clean' before recompiling to ensure a pristine build.",
              default: false
            },
            threads: {
              type: "string",
              description: "Number of compiler threads to run in parallel. Use 'all' for all available CPU cores.",
              default: "all"
            }
          }
        }
      },
      {
        name: "run_qblade",
        description: "Launches the compiled QBlade wind turbine simulation executable.",
        inputSchema: {
          type: "object",
          properties: {
            inputFile: {
              type: "string",
              description: "Absolute path to the configuration or project file to load (.qpr, .sim, .trb, etc.)."
            },
            headless: {
              type: "boolean",
              description: "Runs under virtual framebuffer (xvfb-run) to prevent graphical crashes in headless/server environments.",
              default: true
            },
            timeoutMs: {
              type: "integer",
              description: "Maximum runtime in milliseconds before closing QBlade.",
              default: 15000
            }
          }
        }
      },
      {
        name: "generate_qblade_configs",
        description: "Generates template or custom QBlade configuration files (.sim, .trb, .inp, .afl).",
        inputSchema: {
          type: "object",
          properties: {
            type: {
              type: "string",
              enum: ["simulation", "turbine", "wind", "airfoil"],
              description: "The type of configuration file to generate."
            },
            outputPath: {
              type: "string",
              description: "File path where the generated file should be saved."
            },
            params: {
              type: "object",
              description: "Key-value configuration parameters to override defaults.",
              default: {}
            }
          },
          required: ["type", "outputPath"]
        }
      },
      {
        name: "read_qblade_output",
        description: "Reads and parses a text/tabulated report file generated by QBlade simulation, producing statistical performance summaries.",
        inputSchema: {
          type: "object",
          properties: {
            filePath: {
              type: "string",
              description: "Absolute path to the QBlade simulation output report."
            }
          },
          required: ["filePath"]
        }
      }
    ]
  };
});

// Handle tool calls
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;
  
  try {
    switch (name) {
      case "compile_qblade": {
        const result = await compileQBlade(args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2)
            }
          ]
        };
      }
      
      case "run_qblade": {
        const result = await runQBlade(args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2)
            }
          ]
        };
      }
      
      case "generate_qblade_configs": {
        const result = await generateQBladeConfig(args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2)
            }
          ]
        };
      }
      
      case "read_qblade_output": {
        const result = await parseQBladeOutput(args);
        return {
          content: [
            {
              type: "text",
              text: JSON.stringify(result, null, 2)
            }
          ]
        };
      }
      
      default:
        throw new Error(`Tool not found: ${name}`);
    }
  } catch (error) {
    return {
      isError: true,
      content: [
        {
          type: "text",
          text: `Error executing tool '${name}': ${error.message}`
        }
      ]
    };
  }
});

// Run server using stdio transport
async function run() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("QBlade MCP Server running on stdio.");
}

run().catch((error) => {
  console.error("Fatal error running server:", error);
  process.exit(1);
});
