import fs from "fs";
import path from "path";

/**
 * Generates a key-value plain text configuration file in QBlade's custom format.
 */
function serializeConfig(obj) {
  let lines = [];
  for (const [key, value] of Object.entries(obj)) {
    if (typeof value === "object" && value !== null) {
      if (Array.isArray(value)) {
        // Handle array of strings/objects
        lines.push(`START_${key}`);
        for (const item of value) {
          lines.push(serializeConfig(item));
        }
        lines.push(`END_${key}`);
      } else {
        // Nested block
        lines.push(`START_${key}`);
        lines.push(serializeConfig(value));
        lines.push(`END_${key}`);
      }
    } else {
      lines.push(`${key} ${value}`);
    }
  }
  return lines.join("\n");
}

export async function generateQBladeConfig(options = {}) {
  const { type, outputPath, params = {} } = options;
  
  if (!type || !outputPath) {
    throw new Error("Missing type or outputPath arguments.");
  }
  
  let configContent = "";
  
  if (type === "simulation") {
    const defaultSim = {
      OBJECTNAME: params.name || "Default_Simulation",
      ISOFFSHORE: params.isOffshore !== undefined ? (params.isOffshore ? 1 : 0) : 0,
      TURB_1: [
        {
          TURBNAME: params.turbineName || "Turbine_1",
          TURBFILE: params.turbineFile || "turbine.trb",
          INITIAL_YAW: params.yaw || 0.0,
          INITIAL_PITCH: params.pitch || 0.0,
          INITIAL_AZIMUTH: params.azimuth || 0.0,
          STRSUBSTEP: params.structuralSubsteps || 4,
          RELAXSTEPS: params.relaxationSteps || 100,
          PRESCRIBETYPE: params.prescribeRPMType || 0,
          RPMPRESCRIBED: params.rpmPrescribed || 12.0,
          TINTEGRATOR: params.integratorType || 1,
          STRITERATIONS: params.structuralIterations || 5
        }
      ],
      WIND_NAME: params.windName || "wind.inp",
      WIND_SPEED: params.windSpeed || 8.0,
      TIMESTEP: params.timeStep || 0.1,
      NUM_TIMESTEPS: params.numTimeSteps || 1000,
      STORE_FROM: params.storeFrom || 0.0,
      DENSITY: params.density || 1.225,
      VISCOSITY: params.viscosity || 1.48e-5
    };
    
    // Merge nested overrides if any
    const merged = { ...defaultSim, ...params };
    configContent = serializeConfig(merged);
    
  } else if (type === "turbine") {
    const defaultTurbine = {
      OBJECTNAME: params.name || "Default_Turbine",
      ROTOR_DIAMETER: params.rotorDiameter || 126.0,
      HUB_HEIGHT: params.hubHeight || 90.0,
      NUM_BLADES: params.numBlades || 3,
      PRECONE: params.precone || -2.5,
      SHAFT_TILT: params.shaftTilt || -5.0,
      OVERHANG: params.overhang || -5.0,
      BLADE_FILE: params.bladeFile || "blade.bld",
      TOWER_FILE: params.towerFile || "tower.twr"
    };
    
    const merged = { ...defaultTurbine, ...params };
    configContent = serializeConfig(merged);
    
  } else if (type === "wind") {
    // Generate simple TurbSim inp file template
    configContent = `
-------- TurbSim v2.00.* Input File -------------------------------------------
Simple wind profile generated by QBlade MCP Server.
--------------------------------------------------------------------------------
         123   RandSeed1       - First random seed
      456789   RandSeed2       - Second random seed
       ${params.windSpeed || 8.0}   URef            - Reference wind speed [m/s]
       ${params.hubHeight || 90.0}   RefHt           - Reference height [m]
       ${params.shear || 0.2}   PLexp           - Power law exponent
       ${params.roughness || 0.03}   Z0              - Roughness length [m]
--------------------------------------------------------------------------------
`.trim();
    
  } else if (type === "airfoil") {
    // Basic polar template
    configContent = `
QBlade Airfoil Polar File
Alpha    Cl       Cd       Cm
-10.0    -0.5     0.02     -0.05
-5.0     -0.1     0.01     -0.05
0.0      0.4      0.008    -0.05
5.0      0.9      0.01     -0.05
10.0     1.3      0.018    -0.05
15.0     1.5      0.035    -0.05
20.0     1.1      0.15     -0.05
`.trim();
  } else {
    throw new Error(`Unsupported config type: ${type}`);
  }
  
  const fullPath = path.resolve(outputPath);
  const dir = path.dirname(fullPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  
  fs.writeFileSync(fullPath, configContent, "utf-8");
  return {
    success: true,
    message: `Successfully generated QBlade ${type} config file at ${fullPath}`,
    path: fullPath
  };
}
