import fs from "fs";
import path from "path";

/**
 * Parses space-separated or tab-separated text/report files generated by QBlade.
 * Computes summary statistics (mean, min, max) for numeric columns.
 */
export async function parseQBladeOutput(options = {}) {
  const { filePath } = options;
  
  if (!filePath) {
    throw new Error("Missing filePath argument.");
  }
  
  const resolvedPath = path.resolve(filePath);
  if (!fs.existsSync(resolvedPath)) {
    throw new Error(`File not found at ${resolvedPath}`);
  }
  
  const content = fs.readFileSync(resolvedPath, "utf-8");
  const lines = content.split(/\r?\n/).map(line => line.trim()).filter(line => line.length > 0);
  
  if (lines.length === 0) {
    return {
      success: false,
      message: "The file is empty."
    };
  }
  
  // Attempt to parse headers and data
  // QBlade files usually start with some comment lines starting with #, or they just have headers on the first few lines
  let headerLineIndex = -1;
  let headers = [];
  let dataRows = [];
  let metadata = [];
  
  // Smart delimiter detection: default to tab/comma, fallback to whitespace if neither exists in the entire content
  let delimiter = /[\t,]+/;
  if (!content.includes('\t') && !content.includes(',')) {
    delimiter = /[\s]+/;
  }
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.startsWith("#") || line.startsWith("!") || line.startsWith("-")) {
      metadata.push(line);
      continue;
    }
    
    // First non-comment line that contains letters could be the headers
    if (headerLineIndex === -1 && /[a-zA-Z]/.test(line)) {
      // If the file is tab/comma-separated, a true header line must contain the delimiter.
      // Top metadata lines like "Aerodynamic Output File created..." do not contain tabs/commas.
      if (content.includes('\t') && !line.includes('\t')) {
        metadata.push(line);
        continue;
      }
      if (content.includes(',') && !line.includes(',')) {
        metadata.push(line);
        continue;
      }
      
      headerLineIndex = i;
      headers = line.split(delimiter).map(h => h.trim());
      continue;
    }
    
    // Rows containing numeric data
    const parts = line.split(delimiter).map(p => parseFloat(p));
    if (parts.length > 0 && !parts.some(isNaN)) {
      dataRows.push(parts);
    } else {
      // If we couldn't parse as all-floats, treat as metadata or log lines
      metadata.push(line);
    }
  }
  
  // If we didn't find clear headers, auto-generate them
  if (headers.length === 0 && dataRows.length > 0) {
    headers = dataRows[0].map((_, idx) => `Col_${idx + 1}`);
  }
  
  if (dataRows.length === 0) {
    // If no numeric data rows, return raw metadata/lines
    return {
      success: true,
      message: "File loaded but no structured numerical data rows were found.",
      metadata: lines.slice(0, 100) // Return first 100 lines of raw text
    };
  }
  
  // Compute statistics for each column
  const stats = {};
  headers.forEach((header, colIdx) => {
    const values = dataRows.map(row => row[colIdx]).filter(val => val !== undefined && !isNaN(val));
    if (values.length === 0) return;
    
    const min = Math.min(...values);
    const max = Math.max(...values);
    const sum = values.reduce((a, b) => a + b, 0);
    const mean = sum / values.length;
    
    stats[header] = {
      min,
      max,
      mean,
      count: values.length
    };
  });
  
  return {
    success: true,
    message: `Successfully parsed QBlade output file. Processed ${dataRows.length} rows across ${headers.length} columns.`,
    metadata: metadata.slice(0, 20),
    headers,
    totalRows: dataRows.length,
    statistics: stats,
    sampleRows: dataRows.slice(0, 5).map(row => {
      const obj = {};
      headers.forEach((h, idx) => {
        obj[h] = row[idx];
      });
      return obj;
    })
  };
}
